# Continuity

## Python Implementation

In this notebook, we will learn:

1. Continuous Functions
2. Continuity Conditions
3. Numerical Continuity Check
4. Left-Hand and Right-Hand Limits
5. Removable Discontinuity
6. Jump Discontinuity
7. Infinite Discontinuity
8. Oscillatory Discontinuity
9. Continuity using SymPy
10. Intermediate Value Theorem
11. Continuity in Neural Networks

In [1]:
import numpy as np
import sympy as sp

np.set_printoptions(
    precision=6,
    suppress=True
)

print("Continuity Notebook Loaded Successfully 🚀")

Continuity Notebook Loaded Successfully 🚀


# Continuous Function

A function is continuous if:

$$
\lim_{x \to a} f(x) = f(a)
$$

Example:

$$
f(x)=x^2
$$

In [2]:
def f(x):
    return x**2

x = 2

print("f(2) =", f(x))

f(2) = 4


# Numerical Continuity Check

Approach a point from both sides.

In [3]:
a = 2

left_points = [
    a - 0.1,
    a - 0.01,
    a - 0.001
]

right_points = [
    a + 0.1,
    a + 0.01,
    a + 0.001
]

print("Left Side")

for x in left_points:
    print(
        x,
        f(x)
    )

print("\nRight Side")

for x in right_points:
    print(
        x,
        f(x)
    )

Left Side
1.9 3.61
1.99 3.9601
1.999 3.9960010000000006

Right Side
2.1 4.41
2.01 4.040099999999999
2.001 4.004001


# Continuity Conditions

A function is continuous if:

1. $f(a)$ exists

2. $\lim_{x \to a} f(x)$ exists

3. $\lim_{x \to a} f(x)=f(a)$

In [4]:
a = 2

fa = f(a)

left_limit = f(a - 1e-6)

right_limit = f(a + 1e-6)

print("f(a) =", fa)

print("Left Limit =", left_limit)

print("Right Limit =", right_limit)

f(a) = 4
Left Limit = 3.9999960000010004
Right Limit = 4.000004000001001


# Removable Discontinuity

Consider:

$$
f(x)=
\frac{x^2-1}{x-1}
$$

At:

$$
x=1
$$

the function is undefined.

In [5]:
def removable(x):
    return (x**2 - 1)/(x - 1)

values = [
    0.9,
    0.99,
    0.999,
    1.001,
    1.01,
    1.1
]

for x in values:
    print(
        x,
        removable(x)
    )

0.9 1.9
0.99 1.990000000000001
0.999 1.9989999999999712
1.001 2.0009999999999177
1.01 2.009999999999999
1.1 2.1


# Simplified Function

Factor:

$$
x^2-1=(x-1)(x+1)
$$

Thus:

$$
f(x)=x+1
$$

In [6]:
def simplified(x):
    return x + 1

print(
    simplified(1)
)

2


# Jump Discontinuity

A jump occurs when:

Left Limit ≠ Right Limit

In [7]:
def jump_function(x):

    if x < 0:
        return 1

    return 2

left_limit = jump_function(-0.0001)

right_limit = jump_function(0.0001)

print("Left Limit :", left_limit)

print("Right Limit:", right_limit)

Left Limit : 1
Right Limit: 2


# Infinite Discontinuity

Example:

$$
f(x)=\frac1x
$$

At:

$$
x=0
$$

the function becomes unbounded.

In [8]:
def reciprocal(x):
    return 1/x

values = [
    0.1,
    0.01,
    0.001,
    0.0001
]

for x in values:
    print(
        x,
        reciprocal(x)
    )

0.1 10.0
0.01 100.0
0.001 1000.0
0.0001 10000.0


# Oscillatory Discontinuity

Example:

$$
f(x)=\sin\left(\frac1x\right)
$$

In [9]:
def oscillatory(x):
    return np.sin(1/x)

values = [
    0.1,
    0.01,
    0.001,
    0.0005,
    0.0001
]

for x in values:
    print(
        x,
        oscillatory(x)
    )

0.1 -0.5440211108893698
0.01 -0.5063656411097588
0.001 0.8268795405320025
0.0005 0.930039504416137
0.0001 -0.30561438888825215


# Symbolic Continuity Check using SymPy

In [10]:
x = sp.Symbol('x')

expr = x**2

limit_value = sp.limit(
    expr,
    x,
    2
)

function_value = expr.subs(
    x,
    2
)

print("Limit :", limit_value)

print("Value :", function_value)

Limit : 4
Value : 4


# Checking Continuity Symbolically

In [11]:
continuous = (
    limit_value
    ==
    function_value
)

print(
    "Continuous:",
    continuous
)

Continuous: True


# Intermediate Value Theorem

If a function is continuous on:

$$
[a,b]
$$

it takes every value between:

$$
f(a)
$$

and

$$
f(b)
$$

In [12]:
def f(x):
    return x**2

a = 1
b = 3

print("f(a) =", f(a))

print("f(b) =", f(b))

f(a) = 1
f(b) = 9


# Searching for Intermediate Values


In [13]:
x_values = np.linspace(
    1,
    3,
    20
)

y_values = f(x_values)

print(y_values)

[1.       1.221607 1.465374 1.731302 2.019391 2.32964  2.66205  3.01662
 3.393352 3.792244 4.213296 4.65651  5.121884 5.609418 6.119114 6.65097
 7.204986 7.781163 8.379501 9.      ]


# Continuity and Differentiability

Differentiability implies continuity.

Example:

$$
f(x)=x^2
$$

is both continuous and differentiable.

In [14]:
def derivative(x):

    h = 1e-6

    return (
        f(x+h)
        -
        f(x)
    ) / h

print(
    derivative(2)
)

4.0000010006480125


# Continuous Activation Functions

Neural Networks often use continuous functions.

Examples:

- Sigmoid
- Tanh
- Softplus

In [15]:
def sigmoid(x):

    return (
        1
        /
        (
            1
            +
            np.exp(-x)
        )
    )

inputs = np.array(
    [-3,-2,-1,0,1,2,3]
)

outputs = sigmoid(inputs)

print(outputs)

[0.047426 0.119203 0.268941 0.5      0.731059 0.880797 0.952574]


# Hyperbolic Tangent

In [16]:
inputs = np.array(
    [-3,-2,-1,0,1,2,3]
)

outputs = np.tanh(inputs)

print(outputs)

[-0.995055 -0.964028 -0.761594  0.        0.761594  0.964028  0.995055]


# ReLU Function

$$
ReLU(x)=\max(0,x)
$$

ReLU is continuous but not differentiable at:

$$
x=0
$$

In [17]:
def relu(x):
    return np.maximum(
        0,
        x
    )

inputs = np.array(
    [-3,-2,-1,0,1,2,3]
)

print(
    relu(inputs)
)

[0 0 0 0 1 2 3]


# Continuity in Machine Learning

Continuous functions help:

- Stable optimization
- Better convergence
- Reliable gradients

Most deep learning algorithms assume continuity.

In [18]:
def loss(w):
    return (w - 5)**2

weights = np.arange(
    0,
    11
)

loss_values = loss(weights)

for w, l in zip(
    weights,
    loss_values
):
    print(
        f"Weight={w}, Loss={l}"
    )

Weight=0, Loss=25
Weight=1, Loss=16
Weight=2, Loss=9
Weight=3, Loss=4
Weight=4, Loss=1
Weight=5, Loss=0
Weight=6, Loss=1
Weight=7, Loss=4
Weight=8, Loss=9
Weight=9, Loss=16
Weight=10, Loss=25


# Key Takeaways

✅ Continuous functions have no breaks

✅ Continuity requires:

$$
\lim_{x \to a}f(x)=f(a)
$$

✅ Discontinuities can be:

- Removable
- Jump
- Infinite
- Oscillatory

✅ Differentiability implies continuity

✅ Deep Learning relies heavily on continuous functions